alter_consult_chatbot.settings:
  type: config_object
  label: 'Alter Consult Chatbot settings'
  mapping:
    services:
      type: sequence
      label: 'Services'
      sequence:
        type: mapping
        mapping:
          name:
            type: string
            label: 'Name'
          description:
            type: string
            label: 'Description'
          price:
            type: integer
            label: 'Price'
    market_price_multiplier:
      type: float
      label: 'Market Price Multiplier'