name: Deploy to Pantheon

on:
  push:
    branches:
      - main  # Change to your production branch

jobs:
  deploy:
    name: Build and Deploy to Pantheon
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, dom, curl, gd, zip, json
          ini-values: post_max_size=256M, upload_max_filesize=256M
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install Terminus
        run: |
          curl -L https://github.com/pantheon-systems/terminus/releases/latest/download/terminus.phar -o terminus
          chmod +x terminus
          sudo mv terminus /usr/local/bin/terminus

      - name: Authenticate Terminus
        run: terminus auth:login --machine-token="${{ secrets.TERMINUS_MACHINE_TOKEN }}"

      - name: Set Git user
        run: |
          git config --global user.email "github-actions@pantheon.io"
          git config --global user.name "GitHub Actions"

      - name: Push to Pantheon
        run: |
          PANTHEON_SITE="${{ secrets.PANTHEON_SITE_NAME }}"
          PANTHEON_ENV="dev"  # or test, live

          git remote add pantheon "ssh://codeserver.dev.$PANTHEON_SITE@codeserver.dev.$PANTHEON_SITE.drush.in:2222/~/repository.git"
          git push pantheon HEAD:master --force

      - name: Clear cache
        run: |
          terminus env:clear-cache "${{ secrets.PANTHEON_SITE_NAME }}.dev"

      - name: Run database updates
        run: |
          terminus drush "${{ secrets.PANTHEON_SITE_NAME }}.dev" -- updatedb -y
