name: Deploy to Pantheon Dev

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Build and Deploy to Pantheon
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terminus CLI
        run: |
          curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar
          php installer.phar install
          echo "::add-path::/home/runner/.composer/vendor/bin"
          terminus self:info

      - name: Authenticate Terminus
        run: terminus auth:login --machine-token="${{ secrets.PANTHEON_MACHINE_TOKEN }}"

      - name: Set Git Config
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"

      - name: Pull latest from main and push to Pantheon
        run: |
          git remote add pantheon "ssh://codeserver.dev.${{ secrets.PANTHEON_SITE_NAME }}@codeserver.dev.${{ secrets.PANTHEON_SITE_NAME }}.drush.in:2222/~/repository.git"
          git push pantheon main --force

      - name: Clear cache and run DB updates
        run: |
          terminus env:clear-cache ${{ secrets.PANTHEON_SITE_NAME }}.dev
          terminus drush ${{ secrets.PANTHEON_SITE_NAME }}.dev -- updatedb -y
          terminus drush ${{ secrets.PANTHEON_SITE_NAME }}.dev -- cr

      - name: Post PR Preview Comment
        if: github.event_name == 'pull_request'
        run: |
          echo "Preview available at: https://dev-${{ secrets.PANTHEON_SITE_NAME }}.pantheonsite.io" >> pr_comment.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Slack Notification
        if: always() && env.SLACK_WEBHOOK_URL != ''
        uses: rtCamp/action-slack-notify@v2.3.3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: "Pantheon Deployment"
          SLACK_MESSAGE: |
            Deployment to https://dev-${{ secrets.PANTHEON_SITE_NAME }}.pantheonsite.io complete.
            Status: ${{ job.status }}
