name: Test and Deploy to Pantheon Dev

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup PHP with shivammathur/setup-php@v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: curl, gd, intl, mbstring, mysql, opcache, xml, zip, soap, bcmath, exif, ftp, gettext, pdo, xmlrpc, sqlite3, pgsql, redis, imagick, gmp, ldap, apcu
          tools: composer:v2

      - name: Clean up Composer environment
        run: |
          rm -rf vendor
          rm -f composer.lock
          rm -rf /home/runner/.cache/composer

      - name: Prepare Composer
        run: |
          composer self-update --stable
          composer clear-cache
          composer validate

      - name: Debug PHP and Composer versions (Test Job)
        run: |
          echo "PHP version:"
          php -v
          echo "Which PHP:"
          which php
          echo "Composer version:"
          composer --version
          echo "Which Composer:"
          which composer

      - name: Allow phpstan/extension-installer
        run: composer config allow-plugins.phpstan/extension-installer true

      - name: Allow dealerdirect/phpcodesniffer-composer-installer
        run: composer config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-ansi --no-plugins

      - name: Check for local-php-security-checker
        run: ls -l vendor/bin/local-php-security-checker || true

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit || true

      - name: Run PHPCS
        run: vendor/bin/phpcs || true

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse || true

      - name: Run Security Check
        run: vendor/bin/local-php-security-checker check || true

  deploy:
    needs: test
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-24.04
    environment:
      name: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup PHP with shivammathur/setup-php@v2 (Deploy Job)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: curl, gd, intl, mbstring, mysql, opcache, xml, zip, soap, bcmath, exif, ftp, gettext, pdo, xmlrpc, sqlite3, pgsql, redis, imagick, gmp, ldap, apcu
          tools: composer:v2

      - name: Clean up Composer environment
        run: |
          rm -rf vendor
          rm -f composer.lock
          rm -rf /home/runner/.cache/composer

      - name: Prepare Composer (Deploy Job)
        run: |
          composer self-update --stable
          composer clear-cache
          composer validate

      - name: Debug PHP and Composer versions (Deploy Job)
        run: |
          echo "PHP version:"
          php -v
          echo "Which PHP:"
          which php
          echo "Composer version:"
          composer --version
          echo "Which Composer:"
          which composer

      - name: Allow phpstan/extension-installer
        run: composer config allow-plugins.phpstan/extension-installer true

      - name: Allow dealerdirect/phpcodesniffer-composer-installer (Deploy Job)
        run: composer config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install Dependencies
        run: composer install --prefer-dist --no-dev --optimize-autoloader --no-ansi --no-plugins

      - name: Set up Terminus
        run: |
          curl -L -f -O https://github.com/pantheon-systems/terminus/releases/download/3.1.0/terminus.phar
          chmod +x terminus.phar
          sudo mv terminus.phar /usr/local/bin/terminus
          ls -lh /usr/local/bin/terminus
          file /usr/local/bin/terminus
          head /usr/local/bin/terminus

      - name: Authenticate with Pantheon
        run: terminus auth:login --machine-token=${{ secrets.PANTHEON_MACHINE_TOKEN }}
        env:
          TERMINUS_ALLOW_UNSUPPORTED_NEWER_PHP: 1

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

      - name: Add Pantheon SSH host keys
        run: |
          set -x
          PANTHEON_CODESERVER_HOST="codeserver.dev.${{ secrets.PANTHEON_SITE }}.drush.in"
          PANTHEON_APPSERVER_HOST="appserver.dev.${{ secrets.PANTHEON_SITE }}.drush.in"

          echo "Attempting to add Pantheon SSH host keys..."
          whoami
          pwd
          echo "PANTHEON_SITE: ${{ secrets.PANTHEON_SITE }}"

          echo "Attempting to resolve codeserver hostname: $PANTHEON_CODESERVER_HOST"
          ping -c 3 $PANTHEON_CODESERVER_HOST || echo "Ping to $PANTHEON_CODESERVER_HOST failed. Check hostname and network."
          nslookup $PANTHEON_CODESERVER_HOST
          dig $PANTHEON_CODESERVER_HOST @8.8.8.8
          getent hosts $PANTHEON_CODESERVER_HOST
          nc -vz $PANTHEON_CODESERVER_HOST 2222

          echo "Attempting to resolve appserver hostname: $PANTHEON_APPSERVER_HOST"
          ping -c 3 $PANTHEON_APPSERVER_HOST || echo "Ping to $PANTHEON_APPSERVER_HOST failed. Check hostname and network."
          nslookup $PANTHEON_APPSERVER_HOST
          dig $PANTHEON_APPSERVER_HOST @8.8.8.8
          getent hosts $PANTHEON_APPSERVER_HOST
          nc -vz $PANTHEON_APPSERVER_HOST 2222

          mkdir -p ~/.ssh
          ssh-keyscan -H -p 2222 $PANTHEON_CODESERVER_HOST >> ~/.ssh/known_hosts
          ssh-keyscan -H -p 2222 $PANTHEON_APPSERVER_HOST >> ~/.ssh/known_hosts
          echo "Contents of known_hosts:"
          cat ~/.ssh/known_hosts
          echo "Finished adding Pantheon SSH host keys."

      - name: Push code to Pantheon Dev
        run: |
          git remote add pantheon ssh://codeserver.dev.${{ secrets.PANTHEON_SITE }}@codeserver.dev.${{ secrets.PANTHEON_SITE }}.drush.in:2222/~/repository.git
          git push pantheon main:master --force

      - name: Run database updates and configuration import
        run: |
          terminus drush ${{ secrets.PANTHEON_SITE }}.dev -- updb -y
          terminus drush ${{ secrets.PANTHEON_SITE }}.dev -- cim -y
          terminus drush ${{ secrets.PANTHEON_SITE }}.dev -- cr
          terminus drush ${{ secrets.PANTHEON_SITE }}.dev -- cron