name: Production Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run Security Scanner
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

    - name: Run Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'Alter-Consult'
        path: '.'
        format: 'HTML'
        out: 'reports'

  test:
    needs: security-scan
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: drupal
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, curl, gd, intl, mysql, pdo, zip
        coverage: xdebug

    - name: Run Tests
      run: |
        ./scripts/run-tests.sh

  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-dev --optimize-autoloader

    - name: Setup Monitoring
      run: |
        ./scripts/setup-monitoring.sh
      env:
        NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}

    - name: Deploy to Production
      env:
        PANTHEON_SITE_UUID: ${{ secrets.PANTHEON_SITE_UUID }}
        PANTHEON_MACHINE_TOKEN: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
      run: |
        composer require pantheon-systems/terminus
        ./vendor/bin/terminus auth:login --machine-token=$PANTHEON_MACHINE_TOKEN
        ./vendor/bin/terminus build:env:push $PANTHEON_SITE_UUID.live

    - name: Post-deployment Checks
      run: |
        ./vendor/bin/terminus drush $PANTHEON_SITE_UUID.live -- status
        ./vendor/bin/terminus drush $PANTHEON_SITE_UUID.live -- cr